baseurl: /MCSS
pygments: true
markdown: redcarpet
safe: true

project-name: MCSS
project-url: http://github.com/operatino/MCSS

project-author: <a href="http://rhr.me">Роберт Харитонов</a>
project-author-twitter: <a href="http://twitter.com/operatino">@operatino</a>

cssg-author-title: Css-o-Gram
cssg-author-name: <a href="mailto:eugeny.horoshilov@odnoklassniki.ru">Евгений Хорошилов</a>

res-watch-on-github: Посмотреть проект на
res-download-archive: Скачать в архиве
res-footer: Сайт опубликован с помощью <a href="http://pages.github.com">GitHub Pages</a> на основе <a href="http://jekyllrb.com">Jekyll</a>
res-author: Автор проекта

res-navigation: Навигация
res-navigation-modules: Модули документации
res-navigation-links: Ссылки