baseurl: /MCSS
pygments: true
markdown: redcarpet
safe: true

project-name: MCSS
project-url: http://github.com/operatino/MCSS

cssg-author-title: Css-o-Gram
cssg-author-name: <a href="mailto:eugeny.horoshilov@odnoklassniki.ru">Евгений Хорошилов</a>

res-project-author: <a href="http://rhr.me">Роберт Харитонов</a>
res-project-author-twitter: <a href="http://twitter.com/operatino">@operatino</a>

res-watch-on-github: Посмотреть проект на
res-download-archive: Скачать в архиве
res-footer: Сайт опубликован с помощью <a href="http://pages.github.com">GitHub Pages</a> на основе <a href="http://jekyllrb.com">Jekyll</a>
res-author: Автор проекта

res-navigation: Навигация
res-navigation-modules: Модули документации
res-navigation-links: Ссылки



res-en-project-author: <a href="http://rhr.me">Robert Haritonov</a>
res-en-project-author-twitter: <a href="http://twitter.com/operatino_en">@operatino</a>

res-en-watch-on-github: Checkout project at
res-en-download-archive: Download archive
res-en-footer: This site is published through <a href="http://pages.github.com">GitHub Pages</a> based on <a href="http://jekyllrb.com">Jekyll</a>
res-en-author: Project author

res-en-navigation: Navigation
res-en-navigation-modules: Documentation modules
res-en-navigation-links: Links